# TODO(acumino): Drop this chart in release v1.75
{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: blackbox-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
