apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.authSecretName }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/server-snippet: |
      location /-/reload {
        return 403;
      }
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          service:
            name: alertmanager-client
            port:
              number: 9093
        path: /
        pathType: Prefix
  {{- end }}
