apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: <seed-name>
  namespace: garden # or garden-local (some project namespace)
spec:
  deployment: # gardenlet deployment parameters
    replicaCount: 2
    revisionHistoryLimit: 2
    helm:
      ociRepository:
        url: europe-docker.pkg.dev/gardener-project/releases/gardener/gardenlet/chart:v0.0.0
    # image: # here you can overwrite the gardenlet image itself (typically not needed since the OCI URL above implicitly defines the image/version, but you can, if you want)
    #   repository: europe-docker.pkg.dev/gardener-project/releases/gardener/gardenlet
    #   tag: latest
    #   pullPolicy: IfNotPresent
    # imageVectorOverwrite: | # here you can overwrite the image repos + tags of the components deployed by gardenlet, e.g. etcd-druid, machine-controller-manager, kube-apiserver, <you name it>
    #   Please find documentation in docs/deployment/image_vector.md
    # componentImageVectorOverwrites: |
    #   Please find documentation in docs/deployment/image_vector.md
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 512Mi
    podAnnotations:
      foo: bar
    podLabels:
      foo: bar
    additionalVolumes: []
    additionalVolumeMounts: []
    env: []
    vpa: true
  config: # GardenletConfiguration resource
    apiVersion: gardenlet.config.gardener.cloud/v1alpha1
    kind: GardenletConfiguration
    <See `20-componentconfig-gardenlet.yaml` for more details>
