global:
  # Gardener API server configuration values
  apiserver:
    clusterIdentity: gardener-local
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIC/DCCAeSgAwIBAgIUd3KJKPGTkGRYvaYChqC82b1fYwgwDQYJKoZIhvcNAQEL
      BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjExMjAzMDU1MjAwWhcNMjYx
      MjAyMDU1MjAwWjAWMRQwEgYDVQQDEwtnYXJkZW5lci1jYTCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBAMFQW4e0fLrqdetxnxt7Z5BXIu9AFZiG+6pClzvF
      u4LmkR7UWJE0R0g/S7Wo6c7oh/HRRSQOq2Cvsv4X3sbByZxUNqizep3QquD45/ue
      94LGqNEmPAlg/n7ukrPfL4N0Me8ELG+wed/QWoFbVWW3sLS4rbSwNm1RbAYrFBKC
      aLVaqsguHA1qKo5tWWmMVL5DGHm/b2i6TPhibVQRh4BjpE05AiyLQqwzG8J2JxRD
      JCSvGSIagNKyN1N+DRiS2ZLl5OAAIah0Tzmdb6xjyv6HLdbtr0l/JNSnzejfmaTF
      yjqpI/bnPJYbarCY4qBesLYlKfc2Nz/XxWTWKcr+Z9znt/cCAwEAAaNCMEAwDgYD
      VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPs2Sc8pOmBa
      g6fhQiryos9BYJnqMA0GCSqGSIb3DQEBCwUAA4IBAQBhFr+dzj8rHe8HGiHyBYPl
      tHpF51Rnd6o14uQsEoLtcOPTlk82k6rTe8EyHwkq5IRUVPU1mDBTW/Jq86WuL544
      RMb5oM+b8RllggTwAf3NH0CxV06HGSIdn0Gltzc6g1sXU35Qkys8txi2xIJrjeh1
      pFTGSzmVOwp1JJC8rf3fyrO0vKgpBTCHVAT4BjkA/3f2fcbPsx5804Wz3AqZ67RB
      RnsjWdZrl99bjCqTSZXgtYyUffXy8hkhCZmaOwjJSyYWjspCGl6Mxh2Lmx1Gt/n+
      sozXlClUZu9PJo2ZD9glhwiM9SXbZQ1m/H+hFtn+dZdJgms2xigNyw7kX3MmKgKJ
      -----END CERTIFICATE-----
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIID+zCCAuOgAwIBAgIUahzyLw4Jp3kO11hRbvA2k7acC34wDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjExMjAzMDU1MzAwWhcNMzEx
        MDEyMDU1MzAwWjAdMRswGQYDVQQDExJnYXJkZW5lci1hcGlzZXJ2ZXIwggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCr5KzY6kTnbtlPqach3J9P/afcy3Jd
        RpnCFr8lydv6INpbIM+x02nbGObGTxb4akOSa5xKKB96VNNbDKxDAYGTTaFrGgId
        pSq+buesW42mV24NN9cEdoG5DhboCeUTTwPc8sUZFfQSTvhtFBplfPPcJ76pD3Op
        F9f1Nr/Puwi/QK5qVtZGcYz8kbJwiKGr7NT5iDPesu7hx66Eu1n/oiiGz+8qE15Z
        TL5p8hQCaMR61UFRuukuIXx38lg1ZvmTUBTyAGOd6aNpAIa5oO+KbiSyPiu0GE4j
        HETGOh7RRNxTpARm397z9NBLpGkgv91KxHpbCBRm6CTXFvMpiPWUAij3AgMBAAGj
        ggE4MIIBNDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
        VR0TAQH/BAIwADAdBgNVHQ4EFgQU2EIwE7Mm8C1syHhEQ2i4SEe8TJUwHwYDVR0j
        BBgwFoAU+zZJzyk6YFqDp+FCKvKiz0Fgmeowgb4GA1UdEQSBtjCBs4IJbG9jYWxo
        b3N0ghJnYXJkZW5lci1hcGlzZXJ2ZXKCGWdhcmRlbmVyLWFwaXNlcnZlci5nYXJk
        ZW6CHWdhcmRlbmVyLWFwaXNlcnZlci5nYXJkZW4uc3ZjgiVnYXJkZW5lci1hcGlz
        ZXJ2ZXIuZ2FyZGVuLnN2Yy5jbHVzdGVygitnYXJkZW5lci1hcGlzZXJ2ZXIuZ2Fy
        ZGVuLnN2Yy5jbHVzdGVyLmxvY2FshwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQBx
        k/bQn50euRuGt3+5oYzZ8F5ewhBIftIBbXdCqqHBNv8cnQw97DxuLZ7i/wgF6gw+
        pTdDpUP5tO24Yp5Fv/tSgw48MGs54zhmFXt91nzmjuu8kej757JiP6DyVNbfENig
        SIueJiSSm0N9rLi9GDfQr6ftZccXJH7c9LvPJWJiWny09szJuHkzaDu0cPVm6IFd
        2rKDfqU6JsSdmKE+8SasK2OzG1PibhmU9Vwhcb8Qb5rVjn2MxvqtpoFXExwi33Od
        L3F6D9jdebdKT8KHi3Ft8beFeWqtAZK/i/5X1tcI1VqZM8l3plWwr1NYog3/55D5
        f70xarTkGAkSqvo4/e4F
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAq+Ss2OpE527ZT6mnIdyfT/2n3MtyXUaZwha/Jcnb+iDaWyDP
        sdNp2xjmxk8W+GpDkmucSigfelTTWwysQwGBk02haxoCHaUqvm7nrFuNplduDTfX
        BHaBuQ4W6AnlE08D3PLFGRX0Ek74bRQaZXzz3Ce+qQ9zqRfX9Ta/z7sIv0CualbW
        RnGM/JGycIihq+zU+Ygz3rLu4ceuhLtZ/6Iohs/vKhNeWUy+afIUAmjEetVBUbrp
        LiF8d/JYNWb5k1AU8gBjnemjaQCGuaDvim4ksj4rtBhOIxxExjoe0UTcU6QEZt/e
        8/TQS6RpIL/dSsR6WwgUZugk1xbzKYj1lAIo9wIDAQABAoIBAFSHa4hwC9pTZIIM
        R6gbOiy37Chj06WS5mHPlcgbcBWcukQ96mTkNhYMNNAobH9Uok4KpRzChlg+BoGr
        xbpdrz6k2lA0xf2WD2L+XucfTpUSQYg2gYIsVLaP+yu4UfIg1SF+MPaZGSE3vGrH
        jAOEYtdMpDG264WnuAdaGREqRK7nbOE64hj7shkRPjjiWeZjzvbpL2ZdwpHxvBo8
        8pfo5fidGRvsvS91dPsqpukq0S/v0yMAge/t8bmu2yXcprk2ZYAvpXxZcrH3DzKk
        RS+0hIERiGyWk+sQT7R9nEadetU9D3xWvH4h9scPYgoL2C4KtW0YKGTx52JNTA7D
        AKgBJeECgYEAwYaJAyczKSJjh3dIIU9/CfGlN1VrdOiO+PeQ8xbg3ck2j6j7DuVg
        jIINCWCDOHiJTt0VIgUbI13sgyi4eWg9sCSnlMLzwnBXtZ0PqXFwWMFht5ToFxaI
        gr2RVYe12FjuMuTNxVZzSPJOlj8QffO8jD9Al/TjHOF6GQZvYrRC6WMCgYEA42Jk
        V3XQBAx7s3zq0VB36wl5YmfwgTBAQUrAHNaNhI58eid6i6mJFuzSkIchKtLJffN9
        m9FMfbUzU0/qjFKfAJFRQ6/aJeSYqqbp/LNlyj6IDRAq112hPV9kDcoZyor2mVpe
        KNPySTkx6Szg04VlwwZqL9y6nVt5NxMPysWNIF0CgYEAgwwyXaM+3rz9vu8ENiJZ
        +YbcBUNft9P/dRJX4nT8otMtkkywbZ7gKWWrpEzpruTYvkGxnM7uWJ2ymgKKIRR4
        qX24yWDWpjVi/4Wy5F//3upc3G8GVxQYLshl0RBMEIvwCSCtQtNOz/fdRZrA9TmG
        1UXD3OKkpJr/DlEwPhupL9cCgYEAn+COrPApUq90Sr+KW6I4rwn6TzbF5BAJHd9x
        NNWmq42D+F/Jymlp+rSJWRWqPHH5OpX5u5VuMvU1IV8Pi5qMMdn7SZxbxkj1DwhN
        fWCmMY3GG2lCtisfNAfeUdPITqFmwmzHx+0+bj3I2iqz6gXhhz77aqvIitvGXvMI
        J4q/sAECgYAahxXB7d3BsudhmTnlVfRQQdeW8RvXU3yl0pskdS/ipdbAslZAZJ0f
        xOnF6kt0rlv026kXfIhxvdkDFO3CFj7O6wersRrklc7CsA3H+XILy3qyGldmCYH4
        /wmlItSdyekGBfkRISsY3Q1ZTb34/TZi5Wawi++kxR6/6DHdOfRx3A==
        -----END RSA PRIVATE KEY-----
    etcd:
      servers: https://etcd-client.garden.svc:2379
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIC/DCCAeSgAwIBAgIUd3KJKPGTkGRYvaYChqC82b1fYwgwDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjExMjAzMDU1MjAwWhcNMjYx
        MjAyMDU1MjAwWjAWMRQwEgYDVQQDEwtnYXJkZW5lci1jYTCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAMFQW4e0fLrqdetxnxt7Z5BXIu9AFZiG+6pClzvF
        u4LmkR7UWJE0R0g/S7Wo6c7oh/HRRSQOq2Cvsv4X3sbByZxUNqizep3QquD45/ue
        94LGqNEmPAlg/n7ukrPfL4N0Me8ELG+wed/QWoFbVWW3sLS4rbSwNm1RbAYrFBKC
        aLVaqsguHA1qKo5tWWmMVL5DGHm/b2i6TPhibVQRh4BjpE05AiyLQqwzG8J2JxRD
        JCSvGSIagNKyN1N+DRiS2ZLl5OAAIah0Tzmdb6xjyv6HLdbtr0l/JNSnzejfmaTF
        yjqpI/bnPJYbarCY4qBesLYlKfc2Nz/XxWTWKcr+Z9znt/cCAwEAAaNCMEAwDgYD
        VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPs2Sc8pOmBa
        g6fhQiryos9BYJnqMA0GCSqGSIb3DQEBCwUAA4IBAQBhFr+dzj8rHe8HGiHyBYPl
        tHpF51Rnd6o14uQsEoLtcOPTlk82k6rTe8EyHwkq5IRUVPU1mDBTW/Jq86WuL544
        RMb5oM+b8RllggTwAf3NH0CxV06HGSIdn0Gltzc6g1sXU35Qkys8txi2xIJrjeh1
        pFTGSzmVOwp1JJC8rf3fyrO0vKgpBTCHVAT4BjkA/3f2fcbPsx5804Wz3AqZ67RB
        RnsjWdZrl99bjCqTSZXgtYyUffXy8hkhCZmaOwjJSyYWjspCGl6Mxh2Lmx1Gt/n+
        sozXlClUZu9PJo2ZD9glhwiM9SXbZQ1m/H+hFtn+dZdJgms2xigNyw7kX3MmKgKJ
        -----END CERTIFICATE-----
      tls:
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIDNjCCAh6gAwIBAgIUFxweLC1uDVLdzJy8/SMncMaKmRMwDQYJKoZIhvcNAQEL
          BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjExMjAzMDYxMTAwWhcNMjIx
          MjAzMDYxMTAwWjAdMRswGQYDVQQDExJnYXJkZW5lci1hcGlzZXJ2ZXIwggEiMA0G
          CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+k8TmhhW4fNloXx1vT9i+qzjWjo3G
          4/pkbQUz6ajgroppNHc88aamI+6oRz1hc17erdtLpOh37kJgCJKGGVwjQss12VFP
          6EoXlHEbFdzJ0SxiHlK11oNGL82wUFE1fa88mENOMKz977AnmKSdQQhQrEGZs1uI
          E2aWEEZcbLEh2cMLM0xtNVup5tmTVECgGOcsdbMS5nTHRc9cyR/eSquRNbuz8fKE
          hcRTMu3Mk14gHE1yvvBO/Iw2VYpqeJMk/3TpvKu0g/GB0YTOtubazFpr0HVvgOme
          lwUZbqAIx9DsPlT/PzQd8d0jW9Cc5kELYlNO6LFwSPMBuGA1so88HQg9AgMBAAGj
          dTBzMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMB
          Af8EAjAAMB0GA1UdDgQWBBQLEAx+J9SAfbggMPIxTrtzZWNoMTAfBgNVHSMEGDAW
          gBT7NknPKTpgWoOn4UIq8qLPQWCZ6jANBgkqhkiG9w0BAQsFAAOCAQEAc2f8Na8c
          WaK+eYf/+BgYkrtoM8apisy7FvvrH5BV+ZcAcUo+SdDkcP0ITmG34rrnOuMBadhk
          VJN5NwR4rWO15kRADnqu7Z+UHFfJt/Ibj79dgZbRcpcnRvafKjVqUOAO2qnhLhxe
          Ttni7xmWmjkbeuzHjR4Y79/GBb0kAN1j9B4ZVWa6O0HSFzgX7fIRLGaMWRGWaA6b
          ABsCefy8Q2Z9nXEg6fyIxzuX1idvnOZ2wqaNAGHazBwL8uUBvSRyh0+qfttzCBBg
          +6LLnJ52wq//0qpwYEutwF7dcCy9Zn/lt3nCYQxPhtQCWvl9d200NpNBSOzEcm5u
          ByqwdmeV7qbL3w==
          -----END CERTIFICATE-----
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAvpPE5oYVuHzZaF8db0/Yvqs41o6NxuP6ZG0FM+mo4K6KaTR3
          PPGmpiPuqEc9YXNe3q3bS6Tod+5CYAiShhlcI0LLNdlRT+hKF5RxGxXcydEsYh5S
          tdaDRi/NsFBRNX2vPJhDTjCs/e+wJ5iknUEIUKxBmbNbiBNmlhBGXGyxIdnDCzNM
          bTVbqebZk1RAoBjnLHWzEuZ0x0XPXMkf3kqrkTW7s/HyhIXEUzLtzJNeIBxNcr7w
          TvyMNlWKaniTJP906byrtIPxgdGEzrbm2sxaa9B1b4DpnpcFGW6gCMfQ7D5U/z80
          HfHdI1vQnOZBC2JTTuixcEjzAbhgNbKPPB0IPQIDAQABAoIBAHx2Y0SuUycumooY
          fE/DFOnJRxCQ/zTilRfbP2ec9UbvlsOImUr7AvxEQUwzYnnvcAj8AFlRtOUGfODd
          GFxt2YfJyo87g2gta54kuw2WZKCFdHgMF7ZcB1XiSHIasj69+6EWS/aXwZMCY8go
          X3G4FCcjqKApy+B90yS0Mk+QSMqynZHbgs6oJ/9HnHK/14i2LqZfEF2DeJGx4RGG
          Fum/DCDb3OkN1snbJ0/Z0dlgAalq9SjbP76htjMXoDuGAMYJQ2iIUg9w521pDGGw
          vEAWJ25KjNUu1vJPdkklStaJKTwo8745vdZtFS77wPUnP/9xQUpSWpPHG+NqbKRf
          4w2MSeECgYEA496C2QKnxKfWnRvUweG4HVj92fKn8a1mrBSxNt5NZJ0myLTyl7YV
          aZ/+Bs4sEqHPdUAaDx+eLyRT6IRgW9Gx/MWc6ACcM5AGGkUqB6ps9FVMJ1MrALr7
          PmuWW+KjldOARgbMRwxLN54qFl7KZiZCENrT6//bbXDYMXEdIx1FTjkCgYEA1hqy
          ik+mZt53QenZql3zjVjeLPFOEZJORnv/Pb+EweKHE41VNZforrSchyHliIE1lI7S
          yZiUoz+hvAF2iAj5cvyPbekJQt/FPq3QO2ttpJCIY7ddC2M4Y7FuFq5hbnkUeZiC
          Eer9Oe/F58QOS3r7kRQUW/FJufhDqshcUUxeiiUCgYBe8ty66CxX+Uen92zTzOYW
          9HnyUvY/8e0STxz4q/C7t+/tOdjL9oc9l/kVhNtAeEQlqywwmRAkvJJqFJ7CI8Jy
          fTVARuDPa3ffgmpc/1qfBNvSlwkYKNF/1Py2FN3tFFAi3bpI8Ip3BmSrJZxYrCBj
          PYuIjvgzxg2PrH5jn1K9oQKBgD2QrbhB0QqRe99zPAjWPTtuy2xG8vjwhhuUej+q
          O6V42viPUmo3xUu/Wact4w/Of7a5HvmjK1KJ8JrcHNZfJkOfRisHsIcPS2uLlW4Q
          pRWGDgIGbvXgUQ2xroNNH20h2fZhGT3HwYsQXGsZoDaqJX6BNJ1/k4CrV+Ha/VjP
          SfwVAoGBAIsKW0cwzYew/vIng/IsxcLPibjfhIgh5cfJgsUDO6/2MgaEfVOlIj1I
          OkMKEx5nzr0JC1aO0KOnsjURQW60r2oGKNVKq992NELgvH05sQYdgEvUtkh7Ckuv
          bDjnVr9OiXkKtJL1Yp4YwEh45UcM8GZ36Q/QR2T3Y439QA+NgnIK
          -----END RSA PRIVATE KEY-----
    # speed-up re-deploying of gardener-apiserver
    minReadySeconds: 0
    enableAdmissionPlugins:
    - ShootVPAEnabledByDefault
    # disable audit log
    audit:
      log:
        path: ""
        maxBackup: 0
        maxSize: 0
        policy: ""
    featureGates:
      SeedChange: true
      ShootCARotation: true
      ShootSARotation: true
    resources: {}

  # Gardener admission controller configuration values
  admission:
    enabled: true
    service:
      clusterIP: fc00:10:96::1000
    seedRestriction:
      enabled: true
    config:
      server:
        webhooks:
          bindAddress: 0.0.0.0
          port: 2719
          tls:
            caBundle: |
              -----BEGIN CERTIFICATE-----
              MIIDJjCCAg6gAwIBAgIUUaSpEaJfy6lXiwagtBuGsRr0HtEwDQYJKoZIhvcNAQEL
              BQAwKzEpMCcGA1UEAxMgZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xsZXItY2Ew
              HhcNMjIwNTAzMDY0MjAwWhcNMjcwNTAyMDY0MjAwWjArMSkwJwYDVQQDEyBnYXJk
              ZW5lci1hZG1pc3Npb24tY29udHJvbGxlci1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
              ggEPADCCAQoCggEBAK/aKhVzDGDt5jnIDhHIqgdJpigoBIR0qhRDW0B2GKAURizO
              p/nJzDA98Pjn6XEs6H93u7pGCSi/TE0hyDGwajDKm55xPE4/KSrnb1xubZ9FSBwP
              SYL801yWhrBlCVBUAxDsQ3rbJBH17B6zsZ9UYzAEz+gncm4XYCv02V6Zt6N8HjtK
              T0n0pRiBJBwjQVPXNHUyzZhvlzCDa/gCu5GvLQ1kORcgji9nE6KUbARySCm4clFD
              l4r5Yij8Zp8D8fo0WhmA5+ZEmubJG8SnGxxGpAtwOddjRHZs2YMCJrK8IIasg5AH
              uK/OR2o1uVbpXZLIaC1YyNPgGqj7ar7pUReDBQ0CAwEAAaNCMEAwDgYDVR0PAQH/
              BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFEW+SbKZtbxUpiyOp90M
              9PlXJ2u0MA0GCSqGSIb3DQEBCwUAA4IBAQA8VldEkYcdkvake9SsaSh4DV2V0uJ/
              atElLeGva1YNVoG99YsKGjJbJw+LrIdsguKhKbir7fS/rRAXxKY6cMyc+F0uwbGZ
              RtpaqXOEh/r7fCbuyt2KxAnCvIIbnx0L+TETPoagWsb56TGT7us0mjj9CH8zYlAv
              eYK3m5QDZWQTDzSCunWwQToQPIUibyFkR+BnIF8H0NJ61oDsZP4VH+rOiUaj0v3H
              KKWOXzAusn7RCzXAemXVD02Dx0urpt7z/O00415lvj7MUPfRQJscyySpnK9hkdOs
              1aTC6iwUjozjF1Fe2mANbKWERNaZIoVaTAVhtgMYL0jf2Zr6oZkX22dT
              -----END CERTIFICATE-----
            crt: |
              -----BEGIN CERTIFICATE-----
              MIID6DCCAtCgAwIBAgIUJl4x4/SAELgFsXIGJcWlt9YF70kwDQYJKoZIhvcNAQEL
              BQAwKzEpMCcGA1UEAxMgZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xsZXItY2Ew
              HhcNMjIwNTAzMDY0NDAwWhcNMzIwNDMwMDY0NDAwWjAoMSYwJAYDVQQDEx1nYXJk
              ZW5lci1hZG1pc3Npb24tY29udHJvbGxlcjCCASIwDQYJKoZIhvcNAQEBBQADggEP
              ADCCAQoCggEBAKupPy1XWFSZjbdihItv7RSP7baCAtrDNo0SRXjIk9+tE0rsa1lm
              f8N5IYMl9uKIhHLUbLeoetryrDqm75rUw9DbwB0W0w0Jk16WBFH7E5bQ5nbhJDbs
              s4PfRWpu03p0uEI8dY5XkW3F1hIGlt4kOBOngGLorLe6lF96bbc/wtZCDiEN9JbK
              X1k45fDqIkoO3SbzIohKSe+JMmgD5ZxeqSvzcGKzLtfavShUcQBmGKsnTF1hiN0F
              47+b7HqfAvWwNPiwXSstmlkYn47wHoSTElMHVq17OsCnPWl8ygYQxdsd4p0ETCij
              ujwWemUeW1KMEjs2EM7Wj7NOjcdOQGNSQKkCAwEAAaOCAQUwggEBMA4GA1UdDwEB
              /wQEAwIFIDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1Ud
              DgQWBBTg6DoeCYVVNqetjpL57+7vjInTCTAfBgNVHSMEGDAWgBRFvkmymbW8VKYs
              jqfdDPT5VydrtDCBiwYDVR0RBIGDMIGAgglsb2NhbGhvc3SCHWdhcmRlbmVyLWFk
              bWlzc2lvbi1jb250cm9sbGVygiRnYXJkZW5lci1hZG1pc3Npb24tY29udHJvbGxl
              ci5nYXJkZW6CKGdhcmRlbmVyLWFkbWlzc2lvbi1jb250cm9sbGVyLmdhcmRlbi5z
              dmOHBH8AAAEwDQYJKoZIhvcNAQELBQADggEBAFUkROHqmJmgas6Df3Bj9L0IiZsS
              kZNqa+Qu0o0/5b7ePDAFHg9uiobwchGIfLUvUWovJTPa89jm1yBoVZ6aMIvqQqhg
              jwmof/BtR/nh1MSQjSx+O0raJjVk7xj0Z8fhGs44OAbzsoMec/yldiMLiP0+ybVp
              BGd+9Pcl5/pkngfcLtxPB0Vu/CWaLXCCOa/sOoWOz9kKGLuiizBKIK8ESL7Z0Jtm
              rfqIQ9A0r/d+jjWe3l3+sl56lFQ7agri8O40rBMyDE66BQfvER4ndicjeX4SjaH8
              R/y7S53DvrJ3xsogoQ60ETmqez9OJF+dcdECxqw8J1lebkbD8yz9b03cK3o=
              -----END CERTIFICATE-----
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAq6k/LVdYVJmNt2KEi2/tFI/ttoIC2sM2jRJFeMiT360TSuxr
              WWZ/w3khgyX24oiEctRst6h62vKsOqbvmtTD0NvAHRbTDQmTXpYEUfsTltDmduEk
              Nuyzg99Fam7TenS4Qjx1jleRbcXWEgaW3iQ4E6eAYuist7qUX3pttz/C1kIOIQ30
              lspfWTjl8OoiSg7dJvMiiEpJ74kyaAPlnF6pK/NwYrMu19q9KFRxAGYYqydMXWGI
              3QXjv5vsep8C9bA0+LBdKy2aWRifjvAehJMSUwdWrXs6wKc9aXzKBhDF2x3inQRM
              KKO6PBZ6ZR5bUowSOzYQztaPs06Nx05AY1JAqQIDAQABAoIBADsbbbuJBcsrjFaG
              v6jbg0C/RlS/c4gsC46Lqgwq1HACQlBcE6KW3otKHDXyTo41/5Uie8TJaHQXdyJC
              9OHVPQ+fewkJIOauU2YQNbCcyWP2zkRExZl761wO9vHs8ziJFCEKfFfk4xhvNITE
              bBJVWlG6LUThZQdmYUx29WxRsh7f01rRwwG8Ce3y7yel49HU0DHlttP/MsNkzQxv
              oLMjD5ETyxnYQghJL3IYdHIODKFrCPCuzpDM3dP8ICFTmiM8yzTb5wISLShaBNv9
              Nx9jXXPG7GBjXV+rrbksstei+IMpmwfJPVLN1OX0v3VCd1qRAUt2gz8kLBphEM+Z
              xoQslWECgYEA2C4Le5M7IDhCQUN/h63HFaj4z0oWxgs9Vyw2TPgNyPWjFJx2Czel
              2Y8BI94KWkzGPu+NBOgo8XM2I08ccJ9eT29O958I396dEIkT+Tx1XmjSUyoU9hwH
              yDU2qUTzgPW782V+Mn7nvuzTSKdOZGySMQAwuau7KMVpPjOte54vAw0CgYEAy0fs
              AzfkJxQcluYJS/8J1obfedFLMaMvDxv8Rv+HRqyThBL69Oz47NGeMQoZJMUqAT+M
              JWSogUwr1jjsGrBFb3G/pfY5Sx1mJjMZ2Nu5on/cBpWH6ysoHtzk0IuAmZHivNqt
              aF7kk1+rrw1/OuK0bitYTlZ1dpnjRyyXMUrJPQ0CgYAN4I7OJPpjrBjctaeHHymr
              g0hNjjT+C5SpduYZdMb1wobweMa/G5hi6eIp2kQR3eHQAnKsAPc34Kx2AcsSk7hr
              IvsPvD7GmDS+7f3BPxdNsy7lNctYrR32xSu4G/wBqESjcD10ol7gC7XYcR0AJ1QP
              HzMBiDugd2O1IX4edF4SNQKBgHv4wNa1n0611Tmx0LmoMDfEyUVhfponCuwMBS7H
              Z5iSZuSFLsdwPd8vd2ow3mSuWY+pUa78VEeGTLW4wUUFe1Mb6+Uq5IYKx+FECN9Y
              IT4Y+/aH+vxQtYcc7+6/JQ6DCeRi+J5OQNgf4HRBpvYijCckCBa+Y6SQ9SrS5uII
              2fGBAoGBAKPqoceWtJNPlT/2F8XWde3B9+Yu4v9deTL9hqMcmd3DSQRlstua6pXn
              2gdfX1KfoWJn/MxI5UKf5RZ2ygmNCTqdLFK/5v7zr4aMw5fSxc9Hf0WuKA8EGzfw
              8dNU6RXARJRSWWKk7wAxSoiNZT/L9VdB0DxZNgZiPBNzdSN6ovgG
              -----END RSA PRIVATE KEY-----
    replicaCount: 1
    resources: {}

  # Gardener controller manager configuration values
  controller:
    config:
      server:
        http:
          bindAddress: 0.0.0.0
          port: 2718
    resources: {}

  # Gardener scheduler configuration values
  scheduler:
    config:
      featureGates:
        HAControlPlanes: true

  # General system configuration
  internalDomain:
    provider: local
    domain: internal.local.gardener.cloud
  defaultDomains:
  - provider: local
    domain: external.local.gardener.cloud
