apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: provider-local
helm:
  ociRepository:
    url: europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local/charts/extension
    tag: v0.0.0
  values:
    image: europe-docker.pkg.dev/gardener-project/releases/gardener/extensions/provider-local:v0.0.0
