apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: networking-calico
providerConfig:
  values:
    image:
      # TODO(shafeeqes): Use v1.27.0 image in the resources once it's released.
      # Currently dev image is used to include https://github.com/gardener/gardener-extension-networking-calico/pull/210
      tag: v1.27.0
