apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kyverno/kyverno/releases/download/v1.9.5/install.yaml
- kyverno-poddisruptionbudget.yaml

patchesStrategicMerge:
- kyverno-configmap.yaml
- kyverno-deployment.yaml
