{{- if .Values.vpaEnabled }}
{{- range $i, $pool := .Values.workerPools }}
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "kube-proxy.name" $pool }}
  namespace: {{ $.Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "daemonsetversion" . }}
    kind: DaemonSet
    name: {{ include "kube-proxy.name" $pool }}
  updatePolicy:
    updateMode: "Auto"
{{- end }}
{{- end }}
