vpaEnabled: true
podNetwork: 1.2.3.4/24
kubeconfig: dummy-b64-data-here
#featureGates: {}
#  CustomResourceValidation: true
#  RotateKubeletServerCertificate: false
images:
  alpine: image-repository
podAnnotations: {}

enableIPVS: false

ports:
  metrics: 10249

workerPools:
- name: ""
  kubernetesVersion: 1.15.0
  kubeProxyImage: image-repository:image-tag
- name: cpu-worker
  kubernetesVersion: 1.15.2
  kubeProxyImage: image-repository:image-tag
- name: cpu-worker
  kubernetesVersion: 1.15.1
  kubeProxyImage: image-repository:image-tag
- name: cpu-worker2
  kubernetesVersion: 1.14.8
  kubeProxyImage: image-repository:image-tag
