apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller-registration.yaml

patches:
- patch: |
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-seed
        lifecycle:
          reconcile: BeforeKubeAPIServer
          delete: AfterKubeAPIServer
          migrate: AfterKubeAPIServer
        workerlessSupported: true
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-shoot
        workerlessSupported: true
  target:
    group: core.gardener.cloud
    kind: ControllerRegistration
    name: provider-local
- path: patch-controller-registrations.yaml
