apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: managedseed
  namespace: garden
spec:
  shoot:
    name: managedseed
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      seedConfig:
        spec:
          settings:
            excessCapacityReservation:
              enabled: false
            scheduling:
              visible: false
            verticalPodAutoscaler:
              enabled: false
          ingress:
            controller:
              kind: nginx
