{{- if .Values.coredns.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: coredns
  name: coredns
  namespace: gardener-extension-provider-local-coredns
spec:
  type: NodePort
  selector:
    app: coredns
  ports:
  - name: tcp
    port: 53
    protocol: TCP
    targetPort: 9053
    nodePort: 30053
  - name: udp
    port: 53
    protocol: UDP
    targetPort: 9053
    nodePort: 30053
  {{- with .Values.coredns.ipFamilies }}
  ipFamilies: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.coredns.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
{{- end -}}
