image: kindest/node:v1.27.1

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddresses:
      - 127.0.0.1
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true

networking:
  ipFamily: ipv4
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
