apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: local-ha-single-zone
spec:
  backup:
    provider: local
    region: local
    secretRef:
      name: backup-local
      namespace: garden
  provider:
    type: local
    region: local
    zones:
    - "0"
  dns:
    provider:
      type: local
      secretRef:
        name: internal-domain-local
        namespace: garden
  ingress:
    domain: ingress.local-ha-single-zone.seed.local.gardener.cloud
    controller:
      kind: nginx
  secretRef:
    name: seed-local-ha-single-zone
    namespace: garden
  networks:
    nodes: 172.18.0.0/16
    pods: 10.1.0.0/16
    services: 10.2.0.0/16
    shootDefaults:
      pods: 10.3.0.0/16
      services: 10.4.0.0/16
  settings:
    excessCapacityReservation:
      enabled: false
    scheduling:
      visible: true
    verticalPodAutoscaler:
      enabled: true
