# TODO(shafeeqes): Remove this chart once gardener v1.75 is released
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
---
apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
