# TODO(shafeeqes): Remove this chart once gardener v1.75 is released
{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
