# TODO(shafeeqes): Remove this chart once gardener v1.75 is released
{{- if not .Values.global.pspDisabled }}
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:node-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
