# TODO(shafeeqes): Remove this chart once gardener v1.75 is released
{{- if not .Values.global.pspDisabled }}
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:node-exporter
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
