image: eu.gcr.io/gardener-project/gardener/extensions/provider-local:latest
imagePullPolicy: IfNotPresent

replicaCount: 1

logLevel: info
logFormat: json

resources: {}
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  controlplane:
    concurrentSyncs: 5
  dnsrecord:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  operatingsystemconfig:
    concurrentSyncs: 5
  ingress:
    concurrentSyncs: 5
  service:
    concurrentSyncs: 5
    hostIP: "127.0.0.1"
    zone0IP: "127.0.0.10"
    zone1IP: "127.0.0.11"
    zone2IP: "127.0.0.12"
  backupbucket:
    localDir: "/dev/local-backupbuckets"
    containerMountPath: "/etc/gardener/local-backupbuckets"
  healthcheck:
    concurrentSyncs: 5
  heartbeat:
    renewIntervalSeconds: 30
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []
ignoreResources: false

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

webhookConfig:
  servicePort: 443
  serverPort: 10250

metricsPort: 8080
healthPort: 8081

leaderElection:
  resourceLock: leases

## settings for metrics, e.g. scraping by seed-prometheus
##
metrics:
  ## enable metrics scraping
  ##
  enableScraping: true

coredns:
  enabled: true

gardener:
  version: ""
  gardenlet:
    featureGates: {}
  seed:
    provider: local
