#
# make operator-up SKAFFOLD_MODULE=provider-local SKAFFOLD_PROFILE=local KUBECONFIG=/tmp/virtual-garden-kubeconfig
#
---
apiVersion: operator.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: local
spec:
# kubeconfigSecretRef:
#   name: kubeconfig-to-target-cluster
#   namespace: garden
  gardenlet:
    bootstrap: BootstrapToken
    deployment:
      podLabels:
        networking.resources.gardener.cloud/to-virtual-garden-kube-apiserver-tcp-443: allowed
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      seedConfig:
        spec:
          backup:
            provider: local
            region: local
            secretRef:
              name: backup-local
              namespace: garden
          provider:
            type: local
            region: local
            zones:
              - "0"
              - "1"
              - "2"
          dns:
            provider:
              type: local
              secretRef:
                name: gardener-internal
                namespace: garden
          ingress:
            domain: ingress.local.unmanaged-seed.local.gardener.cloud
            controller:
              kind: nginx
          networks:
            nodes: 172.18.0.0/16
            # Those CIDRs must match those specified in the kind Cluster configuration.
            pods: 10.1.0.0/16
            services: 10.2.0.0/16
            shootDefaults:
              pods: 10.3.0.0/16
              services: 10.4.0.0/16
          settings:
            excessCapacityReservation:
              enabled: false
            verticalPodAutoscaler:
              enabled: false
